### ISSUE TITLE
[Library] : Align component name and parameters to material ones

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-flutter#222] opened 2023-09-28 14:31 UTC
Check from the documentation the differences with the ods-android version and see if we can add the same names

Current Components to be check :

- [ ]  Button icons
- [ ]  FAB*
- [ ]  Segmented Buttons
- [ ]  Bottom sheet*
- [ ]  Cards
- [ ]  Chips*
- [ ]  Dialogs
- [ ]  Menus
- [ ]  Progress indicators*
- [x]  Sliders*
- [ ]  Snackbars*
- [ ]  Text fields

to be check and updated now

**Comment by B3nz01d** [comment] 2023-11-07 08:26
Duplicate of #224

**Closed by B3nz01d** 2023-11-07 08:26 UTC
Labels: 📖 documentation, ⚛️ Component
